### ISSUE TITLE
Extra information around SameSite cookies and CSRF

### ISSUE THREAD

**Issue by Glazy** [pilcrowOnPaper/copenhagen#12]
The "Sessions" guide contains the following:

> CSRF protection must be implemented when using cookies, and using the SameSite flag is not sufficient.

This is _somewhat_ true, but there is some additional nuance here.

My understanding is that `SameSite=Lax` (or `Strict`) _is_ sufficient CSRF protection if the following conditions are met:

* The user's browser supports it. Global support is currently [~96%](https://caniuse.com/same-site-cookie-attribute)
* `GET` requests aren't used to mutate data on the server.
* The website/application doesn't surface user-generated content (such as the ability to post links, forms, etc).

As with anything related to auth, there are plenty of edge-cases (as listed above) but generally I think `SameSite=Lax` or `SameSite=Strict` _could_ be recommended as a sufficient method of CSRF protection in certain circumstances.

Interested to hear your thoughts and, if you agree, I'm happy to modify the "SameSite cookie attribute" section of the "CSRF" guide to include this info.

**Comment by pilcrowOnPaper** [comment]
It's partially mentioned in the CSRF page:

> Additionally, as this flag is relatively new and only protects against cross-site request forgery (instead of cross-origin request forgery), this should not be the only layer of defense.

Though, we should probably mention about the 96%

**Comment by Glazy** [comment]
Closing this issue as a result of #15 being merged!
