### ISSUE TITLE
Language version

### ISSUE THREAD

**Issue by SxYxuse** [pilcrowOnPaper/copenhagen#20]
Hey man, i follow your work since a while now, i read your copenhagen book few times and i wanted to know if you allow me to rewrite it in french. With the aim of facilitating French-speaking students and extending its impact. I'm a student like you who wants to improve and discover new things.

Thank you.

**Comment by pilcrowOnPaper** [comment]
Maintaining multiple languages is a big task that I probably don't have time for. That said, it's MIT licensed so as long as you credit the project, you're free to do anything with it. And we could probably add a link to your translation as a community maintained project

**Comment by SxYxuse** [comment]
Hi,

Thank you for your response. I appreciate your permission to proceed with the translation. I'll create a French version of your work and ensure to credit your project properly. I'll keep you updated on the progress after my exams.

Thanks again!

SxYxuse

**Comment by SxYxuse** [comment]
@pilcrowOnPaper I've finished a first version: [(https://copenhagen.sxyxuse.dev/content/index)], I hope you like the interface, for the content I'm translating word by word so the quality has been maintained, thanks for your feedback

**Comment by pilcrowOnPaper** [comment]
@SxYxuse Holy shit, that's awesome!

**Comment by pilcrowOnPaper** [comment]
Gonna close this for now
