### ISSUE TITLE
Seems like the domain is blocked in the UK

### ISSUE THREAD

**Issue by mokshsinghji** [pilcrowonpaper/copenhagen#24]
Hi,

I found a link to your website from Lucia Auth, and I thought your website was down at first, but then as soon as I used a VPN (location of Switzerland), it worked immediately. Perhaps there isn't something you can do, but I thought it may be useful to inform you. 😄

**Comment by pilcrowOnPaper** [comment]
It is still blocked?

**Comment by mokshsinghji** [comment]
yup
