### ISSUE TITLE
Increase recommended entropy of tokens

### ISSUE THREAD

**Issue by randomstuff** [pilcrowonpaper/copenhagen#26]
The current text is:

> Tokens should have at least 112 bits of entropy (120-256 is a good range). […] UUID v4 may fit these requirements (122 bits of entropy), […]

OAuth [says](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-09.html#section-7.8):

> The probability of an attacker guessing generated tokens (and other credentials not intended for handling by end-users) MUST be less than or equal to 2^(-128) and SHOULD be less than or equal to 2^(-160).

OAuth and OpenID connect are widely used. If you use 160 bits of entropy for the OAuth tokens, it would be weird to use only 112 bits of entropy for other tokens. I would suggest raising this value to 128 or 160 bits which makes the tokens conforming with the requirements of Oauth/OpenID Connect.

That would imply recommending against using UUIDs which is probably not a bad idea. Using an UUID could encourage receiving applications to use UUID types for managing the token (eg. relational database column type) whereas the token should be seen as an opaque string.

**Comment by pilcrowonpaper** [comment]
OWASP [recommends](https://owasp.org/www-community/vulnerabilities/Insufficient_Session-ID_Length#:~:text=Session%20identifiers%20must%20have%20at,or%20unpredictability%20in%20a%20value) 64 bits. The 112 bits number is from the [NIST](https://csrc.nist.gov/pubs/sp/800/131/a/r2/final). I think the current recommendation of 120-256 is sufficient

**Comment by randomstuff** [comment]
FWIW, the new [NIST SP 800-131Ar3](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar3.ipd.pdf) draft moves away from 112 bits of entropy (deprecated after 2030) to 128 bits.
