### ISSUE TITLE
Guidance is very oriented around "roll your own" which is the first don't rule of security

### ISSUE THREAD

**Issue by identitymonk** [pilcrowonpaper/copenhagen#29]
We are dealing with an important security domain here and most of content presented, with the objective of explaining the underlying mechanisms, fell short of ensuring a secure end state as the readers are left with the burden of the implementation.

Each parameter of one implementation can go wrong and that is why libraries and packaged solutions exist so that you don't have to roll your own... and fail.

This guide needs more references outside of OWASP and more references on certified components offloading the risk of misconfiguration for the readers.

**Comment by jorgerodrigues** [comment]
The point above is true. However, that doesn't make packaged solutions the right response. The guides provide,as it stands, a very concise and to the point explanation of good practices when implementing these things.

As I see it, it would be a disservice to the goal of the guides to refer to pre-packaged solutions and abstract away the learning that it is trying to provide.

**Comment by pilcrowonpaper** [comment]
The book is intended for people who want to implement auth from scratch or just curious of how it works. There are already enough resources on using pre-existing solutions. The book is not for people who "just" want something that works out of the box.

**Comment by identitymonk** [comment]
Still, you don't reimplement cryptography.... you use and reference libs.
