### ISSUE TITLE
Invalidate sessions after password reset

### ISSUE THREAD

**Issue by OverHash** [pilcrowonpaper/copenhagen#31]
Many sources (e.g., [owasp](https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html#user-resets-password)) include an additional step during password reset:

> Ask the user if they want to invalidate all of their existing sessions, or invalidate the sessions automatically.

This step probably deserves to be mentioned in the https://thecopenhagenbook.com/password-reset page.

**Comment by bishr-jeeves** [comment]
Would it be better to just invalidate all existing sessions by default?

**Comment by OverHash** [comment]
> Would it be better to just invalidate all existing sessions by default?

I'm certainly no expert, but I choose to make users opt-out of invalidating existing sessions when they reset their password, so yes.

**Comment by pilcrowonpaper** [comment]
Thanks, updated the page on password reset. I'm not sure if there are benefits to asking the user if they want to invalidate all their sessions tho. Most people would assume password change = sign in again.
