### ISSUE TITLE
No mention of FIDO2 passkeys as a passwordless authentication mechanism

### ISSUE THREAD

**Issue by identitymonk** [pilcrowonpaper/copenhagen#34]
[FIDO2 Passkey](https://fidoalliance.org/passkeys/) is the new way to authenticate users in Identity Providers: 

[Apple](https://support.apple.com/en-ca/guide/iphone/iphf538ea8d0/ios)
[Google](https://www.google.com/account/about/passkeys/)
[Microsoft](https://support.microsoft.com/en-us/account-billing/signing-in-with-a-passkey-09a49a86-ca47-406c-8acc-ed0e3c852c6d)

Implementation should follow WebAuthN guidelines: https://webauthn.io/

**Comment by pilcrowonpaper** [comment]
https://thecopenhagenbook.com/webauthn
?

**Comment by identitymonk** [comment]
my bad
