### ISSUE TITLE
Signed CSRF cookies must be session bound

### ISSUE THREAD

**Issue by matt-allan** [pilcrowonpaper/copenhagen#41]
The docs recommend signing double submit cookies to protect against subdomain attacks:

> Regular double-submit cookies that aren't signed will still leave you vulnerable if an attacker has access to a subdomain of your application's domain. This would allow them to set their own double-submit cookies

However, the signature is only of the random token:

```go
 mac := hmac.New(sha256.New, secret)
mac.Write([]byte(csrfToken))
csrfTokenHMAC := mac.Sum(nil)
```

This does not prevent an attacker from injecting their own cookies. It only adds an additional step, where they first have to make a request to get a valid cookie.

The only way that signing helps is if it prevents an attacker from substituting a cookie they obtained from another session. Including the session id in the mac (but not in the cookie) would work.

**Comment by pilcrowonpaper** [comment]
Yup, true - thanks!

**Comment by pilcrowonpaper** [comment]
Fixed
